function data()
return {
	en = {

		["mod_name"] = "Sliding wall cars with 4 axles (G1 profile)",
		["mod_desc"] = "In the early 1970s, the first prototypes of four-axle sliding-wall wagons were introduced, which stood out at the time due to their large loading areas for palletized cargo. Nowadays, these wagons have become indispensable. This package includes a significant portion of four-axle sliding-wall wagons with G1 profile (standard size) that have been in use over the past decades. Starting with the prototypes from 1973, various paint schemes in the mid-1980s, and up to the modern Habbis wagons of AAE, built in 1995.",
		["HB1_desc"] = "In 1976, Waggonfabrik Uerdingen (DUEWAG) developed a sliding wall wagon with four axles and three walls on each side, which allowed the wagon to be opened by one third from both sides. Initially, these wagons were supplied in limited numbers to Eisenbahnverkehrsmittel-AG (EVA), but later they went to the then newly founded company Cargowaggon. Cargowaggon was created in 1979 through a tender to manufacture and manage new rail cars for Ford Europe to facilitate the transport of vehicle parts between different European factories. However, the wagons were soon replaced by other models such as Habins 3, and the last examples were retired or sold by the 1990s. Today, isolated wagons can still be found in Romania (GFR).",
		["HB2_desc"] = "One of the first large, four-axle H cars with several sliding walls, built approx. 1973 by Waggon-Union Siegen). The only adjusters at that time were Railship and Transwaggon. At the end of the 1970s, DB needed additional ss-capable sliding wall cars since the establishment of its postal freight train network and thus leased HB2 from TWA. These postal express cars were redesignated as Habiqss and received their own paint scheme with a postal emblem starting in 1977. After the discontinuation of the rail mail service (and later also the liquidation of Railship), all wagons came (back) to TWA. Nowadays, however, these cars are rarely seen, but most models continue to run in Romania (bought up by GFR, among others).",
		["HB3_desc"] = "In 1984, WU Siegen built a series of several different sliding wall wagons for Eisenbahnverkehrsmittel-AG (EVA), including the Habins 3. All wagons were operated under the Frankfurt-based company Cargowaggon (founded in 1979), which specialized in the purchase of wagons for subleasing them to other customers (e.g. BMW).  In 1998, Cargowaggon was bought by GERS and its fleet was taken over. The Habins 3 changed hands several times since then (GERS - DB - GERS - TOUAX), but can still be found today.",		
		["HBAAE_desc"] = "Following a prototype, the Ahaus-Alstätter-Eisenbahn (AAE) procured over 1,000 Habbins sliding wall cars (AAE types H1 and H3) in 1995, which were built at Waggonbau Niesky in cooperation with Tatravagonka Poprad until 1999. These were leased to numerous customers throughout Europe. In 1996, DB AG also leased a total of 390 of these cars, but they were unrecognizable as DB vehicles because they continued to operate under the AAE regime (68 AAE). Although many of the former SJ and Nordwaggon AAE cars were also later purchased by ÖBB, the latter nevertheless additionally owned its own slightly modified variants of the Habbin as early as 1998. In 2015, AAE was bought out by VTG, and the cars now operate under AAEC.",
		["HB345_desc"] = "In 1987, DB procured 100 bogie sliding wall cars from WU Siegen. DB lined up 50 cars, each with eight interlocking partitions, as Habbikks-tt 346 - redesignated as Habbills 346 until 1993. In 1997, DB AG prepared a car as a test car for transporting paper rolls; at the same time, the Habbis 345 276 7 013 selected for this purpose received a traffic red paint scheme - the only car of this type to date.",
		["HB6_desc"] = "In the early 1980s, Transwaggon procured a series of modern sliding-wall cars with three sliding walls per side. Like their predecessors, these cars were used for transporting large-volume, light goods as well as cardboard boxes and packaging materials. Some companies, such as Opel and Viessmann, also included wagons of this type in their fleets in the mid-1980s, although Viessmann's variant (HB63) required slight modifications. These distinctive variants all disappeared in the early 2000s, and today the cars are owned exclusively by Transwaggon and ERR.",
		["HB901_desc"] = "After Swedish Transport Company Nordwaggon underwent a restructuring in 1990, the company made the decision to add four-axle covered bogie cars, known as Habins, to its fleet. Between 1992 and 1994, a total of 203 Habins 901 were delivered by Transtech, a Finnish company. When Transwaggon took over Nordwaggon, the cars were taken over, with only the addresses changed. They are still recognizable as former Nordwaggon wagons and are still in service today under TWA.",
		["sound_check"] = "Activate custom sound?",
		["HBSBB_desc"] = "In 1977, Schindler Waggon AG, Pratteln delivered 100 four-axle sliding wall cars to SBB as Habis-x 31 85 275 0 100-199. Since 1987, the type designation has been Habils. Between 2004 and 2010, around 50 cars were sold or discarded.",
		["HBSNCF_desc"] = "These cars are part of a series of 500 sliding wall cars numbered 31 87 285 0 000-6 to 0 499-0 .Habiss 9.16, renumbered 21 87 027 9 000-5 to 499-9 P under EVS management. Built 1970-1971 by Ateliers du Construction du Nord de la France (ANF). From 1971-1972, the French ANF also delivered 100 1st generation 4-axle sliding wall cars to SBB.",
		["height"] = "Height",
		["height_tooltip"] = "Configure height",
		["jrm_param_offsetx_tooltip"] = "Configure offset",
		["jrm_param_type_tooltip"] = "Type",
		["offset x-axis"] = "Offset x-axis",
		["ground"] = "Ground",
		["rail"] = "Rail",
		["vehicle"] = "Vehicle",
		["Dreplaced"] = "Door replaced",
		["Schiebewandwagen"] = "Sliding Wall Cars",
		

		
	},

	de = {

		["mod_name"] = "Schiebewandwagen vierachsig (G1 Profil)",
		["mod_desc"] = "In den frühen 1970er Jahren wurden die ersten Prototypen von vierachsigen Schiebewandwagen eingeführt, die damals durch ihre großvolumigen Laderäume für palettierte Fracht auffielen. Heutzutage sind diese Wagen jedoch unverzichtbar geworden. In diesem Paket sind zahlreiche vierachsige Schiebewandwagen mit G1-Profil (Normalgröße) enthalten, die in den letzten Jahrzehnten zum Einsatz kamen. Sie reichen von den Prototypen aus dem Jahr 1973 über verschiedene Lackierungen in den 1980er Jahren bis hin zu den modernen Habbis der AAE, die im Jahr 1995 gebaut wurden.",
		["HB1_desc"] = "Im Jahr 1976 entwickelte die Waggonfabrik Uerdingen (DUEWAG) einen Schiebewandwagen mit vier Achsen und drei Wänden auf jeder Seite, was eine Öffnung des Wagens um ein Drittel von beiden Seiten ermöglichte. Anfangs wurden diese Wagen in begrenzter Stückzahl an die Eisenbahnverkehrsmittel-AG (EVA) geliefert, später gingen sie an das damals neu gegründete Unternehmen Cargowaggon. Cargowaggon entstand 1979 durch eine Ausschreibung zur Herstellung und Verwaltung neuer Schienenfahrzeuge für Ford Europa, um den Transport von Fahrzeugteilen zwischen verschiedenen europäischen Fabriken zu erleichtern. Die Wagen wurden jedoch bald durch andere Modelle wie z.B. Habins 3 ersetzt, die letzten Exemplare wurden bis in die 90er Jahre ausgemustert bzw. verkauft. Heute können noch vereinzelte Wagen in Rumänien gefunden werden (GFR).",
		["HB2_desc"] = "Einer der ersten großen, vierachsigen H-wagen mit mehreren Schiebewänden, gebaut ca. 1973 von Waggon-Union Siegen. Einsteller waren zu dieser Zeit lediglich Railship und Transwaggon. Ende der 70er Jahre benötigte die DB seit Einrichtung ihres Post-Güterzugnetzes zusätzliche ss-fähige Schiebewandwagen und mietete somit HB2 von TWA an. Diese Post-Schnellläufer wurden als Habiqss umbezeichnet und bekamen ab 1977 ihre eigene Lackierung mit Postemblem. Nach Wegfall des Bahnpostverkehrs (und später ebenso der Liquidierung von Railship) kamen alle Waggons (zurück) zu TWA. Heutzutage sind diese Wagen in Deutschland und Umgebung selten anzutreffen, die meisten Modelle laufen aber weiterhin in Rumänien (u.A. von GFR aufgekauft).",
		["HB3_desc"] = "1984 baute WU Siegen für die Eisenbahnverkehrsmittel-AG (EVA) eine Serie mehrerer verschiedener Schiebewandwagen, unter Anderem den Habins 3. Alle Wagen liefen dabei unter dem Frankfurter Unternehmen Cargowaggon (gegründet 1979), welches sich auf den Kauf von Waggons zur Untervermietung an weitere Kunden (bspw. BMW) spezialisierte.  1998 wurde Cargowaggon von GERS aufgekauft, und dessen Fuhrpark übernommen. Die Habins 3 wechselten seitdem mehrmals die Besitzer (GERS - DB - GERS - TOUAX), sind aber bis heute vereinzelt anzutreffen.",
		["HBAAE_desc"] = "Nach einem Prototypen beschaffte die Ahaus-Alstätter-Eisenbahn (AAE) 1995 über 1000 Schiebewandwagen der Bauart Habbins (AAE-Typen H1 und H3), die bis 1999 bei Waggonbau Niesky in Zusammenarbeit mit Tatravagonka Poprad entstehen. Diese wurden an zahlreiche Kunden europaweit vermietet. 1996 mietet auch die DB AG insgesamt 390 dieser Wagen an, die jedoch als DB-Fahrzeuge nicht zu erkennen sind, da sie weiter unter AAE-Regime (68 AAE) verkehren. Obwohl später ebenfalls viele der ehemaligen SJ und Nordwaggon AAE Waggons von der ÖBB aufgekauft wurden, besaß diese dennoch bereits ab 1998 zusätzlich ihre eigenen, leicht abgeänderten Varianten des Habbins. 2015 wurde die AAE von der VTG aufgekauft, die Wagen verkehren nun unter AAEC.",
		["HB345_desc"] = "1987 beschafft die DB bei der WU Siegen 100 Drehgestell-Schiebewandwagen. 50 Wagen mit je acht verriegelbaren Trennwänden reihte die DB als Habbikks-tt 346 ein – bis 1993 zu Habbills 346 umgezeichnet. 1997 richtete die DB AG einen Wagen als Versuchswagen zum Transport von Papierrollen her; dabei erhielt der hierfür ausgewählte Habbis 345 276 7 013 gleichzeitig – als bislang einziger Wagen dieser Bauart – einen verkehrsroten Anstrich.",
		["HB6_desc"] = "In den frühen 1980er Jahren beschaffte Transwaggon eine Reihe moderner Schiebewandwagen mit drei Schiebewänden pro Seite. Diese Wagen wurden ebenso wie ihre Vorgänger für den Transport von großvolumigen, leichten Gütern sowie für den Transport von Kartonagen und Verpackungsmaterial eingesetzt. Einige Unternehmen wie Opel und Viessmann nahmen in den mittleren 1980er Jahren ebenfalls Wagen dieser Art in ihre Flotten auf, wobei die Variante von Viessmann (HB63) leichte Anpassungen erforderte. Diese markanten Varianten verschwanden alle zu Beginn der 2000er Jahre, und heute befinden sich die Wagen ausschließlich im Besitz von Transwaggon und ERR.",
		["HB901_desc"] = "Nachdem das schwedische Unternehmen Nordwaggon im Jahr 1990 eine Umstrukturierung durchlief, traf das Unternehmen die Entscheidung, seine Flotte um vierachsige gedeckte Drehgestellwagen, bekannt als Habins, zu erweitern. Zwischen 1992 und 1994 wurden insgesamt 203 Habins 901 von Transtech, einem finnischen Unternehmen, geliefert. Als Transwaggon Nordwaggon übernahm, wurden die Wagen übernommen, wobei lediglich die Anschriften geändert wurden. Als ehemalige Nordwaggon-Waggons sind sie weiterhin erkennbar und sind bis heute unter TWA im Einsatz.",
		["HBSBB_desc"] = "1977 lieferte die Schindler Waggon AG, Pratteln 100 vierachsige Schiebewandwagen als Habis-x 31 85 275 0 100-199 an die SBB. Seit 1987 ist die Typenbezeichnung Habils. Zwischen 2004 und 2010 wurden rund 50 Wagen verkauft oder ausrangiert.",
		["HBSNCF_desc"] = "Diese Wagen gehören zu einer Serie von 500 Schiebewandwagen mit den Nummern 31 87 285 0 000-6 bis 0 499-0 .Habiss 9.16, die unter der EVS-Leitung 21 87 027 9 000-5 bis 499-9 P umnummeriert wurden. Gebaut 1970-1971 von Ateliers du Construction du Nord de la France (ANF). Von 1971-1972 lieferten die französischen ANF ebenfalls 100 Wagen der 1. Generation 4achsiger Schiebewandwagen an die SBB.",
		["sound_check"] = "Eigenes Soundset aktivieren?",
		["height"] = "Höhe",
		["height_tooltip"] = "Höhe einstellen",
		["jrm_param_offsetx_tooltip"] = "Versatz einstellen",
		["jrm_param_type_tooltip"] = "Typ",
		["offset x-axis"] = "Verschub X-Achse",
		["ground"] = "Boden",
		["rail"] = "Gleis",
		["vehicle"] = "Fahrzeug",
		["Dreplaced"] = "Wand ersetzt",
		["Schiebewandwagen"] = "Schiebewandwagen",
        
	},
}
end
